## PCA 

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [3]:
df=pd.read_csv("regression_cleaned_data.csv")
df=df.drop(['Unnamed: 0'],axis=1)

In [4]:
y= df.iloc[:,0] #independent feature
X = df.iloc[:, 1:] #dependent feature

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)


Transformation

In [19]:
pca=PCA(n_components=0.95) 
# capturing 95% of variance

In [20]:
X_train=pca.fit_transform(X_train)

In [21]:
X_train

array([[-142.32377804,  -22.41153502],
       [-143.04950163,   18.1747509 ],
       [-119.49967663,  -50.38684852],
       ...,
       [  27.94191805,    4.01547688],
       [ 122.82656826,   52.39419399],
       [ -63.91244561,    2.95573463]])

In [22]:
pca.components_

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-0.0000000e+00,  1.0000000e+00,  6.7315105e-18, -8.1022890e-17]])

In [23]:
pca.explained_variance_ratio_

array([0.9019896 , 0.07079424])